---
- name: Установка и настройка ELK для одиночной ноды
  hosts: all
  become: yes

  vars:
    elastic_version: "8.x"
    kibana_index: "syslog-%{+YYYY.MM.dd}"

  tasks:

  - name: Установить зависимости
    apt:
      name:
        - apt-transport-https
        - curl
        - gnupg
        - lsb-release
        - unzip
      state: present
      update_cache: yes

  - name: Добавить репозиторий Elastic
    ansible.builtin.shell: |
      curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /usr/share/keyrings/elastic-archive-keyring.gpg
      echo "deb [signed-by=/usr/share/keyrings/elastic-archive-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main" | tee /etc/apt/sources.list.d/elastic-8.x.list
    args:
      creates: /etc/apt/sources.list.d/elastic-8.x.list

  - name: Установить Elasticsearch, Kibana и Logstash
    apt:
      name:
        - elasticsearch
        - kibana
        - logstash
      state: present
      update_cache: yes

  - name: Настроить elasticsearch.yml
    copy:
      dest: /etc/elasticsearch/elasticsearch.yml
      content: |
        cluster.name: elk-cluster
        node.name: elk-node-1
        path.data: /var/lib/elasticsearch
        path.logs: /var/log/elasticsearch

        network.host: 0.0.0.0
        transport.host: 0.0.0.0
        discovery.type: single-node

        xpack.security.enabled: true
        xpack.security.enrollment.enabled: true
        xpack.security.transport.ssl.enabled: false
        xpack.security.http.ssl.enabled: false

  - name: Исправить права каталогов Elasticsearch
    file:
      path: "{{ item }}"
      owner: elasticsearch
      group: elasticsearch
      recurse: yes
    loop:
      - /var/lib/elasticsearch
      - /var/log/elasticsearch

  - name: Включить и запустить Elasticsearch
    systemd:
      name: elasticsearch
      enabled: true
      state: started

  - name: Ждать пока Elasticsearch станет доступен
    uri:
      url: "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=120s"
      status_code: 200
    register: es_status
    retries: 12
    delay: 10
    until: es_status.status == 200

  - name: Создать enrollment token для Kibana
    command: /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana
    register: kibana_token
    changed_when: false

  - name: Настроить kibana.yml с enrollment token
    copy:
      dest: /etc/kibana/kibana.yml
      content: |
        server.host: "0.0.0.0"
        elasticsearch.hosts: ["http://localhost:9200"]
        elasticsearch.enrollment_token: "{{ kibana_token.stdout_lines[0] }}"

  - name: Включить и запустить Kibana
    systemd:
      name: kibana
      enabled: true
      state: started

  - name: Настроить logstash.conf
    copy:
      dest: /etc/logstash/conf.d/syslog.conf
      content: |
        input {
          file {
            path => "/var/log/syslog"
            start_position => "beginning"
            sincedb_path => "/dev/null"
          }
        }

        filter {
          grok {
            match => { "message" => "%{SYSLOGBASE} %{GREEDYDATA:syslog_message}" }
          }
        }

        output {
          elasticsearch {
            hosts => ["http://localhost:9200"]
            user => "elastic"
            password => "changeme"  # при одиночной ноде можно временно
            index => "{{ kibana_index }}"
          }
          stdout { codec => rubydebug }
        }

  - name: Проверить конфигурацию Logstash
    command: /usr/share/logstash/bin/logstash --config.test_and_exit -f /etc/logstash/conf.d/syslog.conf
    register: logstash_conf
    failed_when: "'Configuration OK' not in logstash_conf.stdout"

  - name: Включить и запустить Logstash
    systemd:
      name: logstash
      enabled: true
      state: started

  - name: Вывести URL для Kibana
    debug:
      msg: "Kibana доступна по адресу: http://{{ ansible_default_ipv4.address }}:5601"
