- name: Установка и настройка nginx
  hosts: nginx
  become: yes
  vars:
    nginx_port: 8080

  tasks:
    - name: Установить nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Скопировать конфигурацию nginx из шаблона
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
      notify:
        - Перезапустить nginx

    - name: Включить nginx в systemd
      ansible.builtin.service:
        name: nginx
        enabled: true

  handlers:
    - name: Перезапустить nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
